### ISSUE TITLE
2.5.08 message.txt update

### ISSUE THREAD

**Issue by ponapalt** [steve02081504/ssp-sinicization#1]
English message.txt diff:

@@ -53,6 +53,9 @@
 info.gcsakura.nocraftman,One of craftman/craftmanw/craftmanurl entries not found. Can't register ghost that has incomplete creator information.
 info.gcsakura.disconnect,Can't connect to Ghost Capter Sakura server.
 
+info.archivepassword.first,This archive/NAR is password protected.\nPlease input password.
+info.archivepassword.retry,Password mismatch.\nPlease input correct password.
+
 //Resource
 resource.common.yesno,Yes,No
 resource.common.okcancel,OK,Cancel

@@ -134,3 +137,4 @@
 log.moduleerror,Communication error. Possible file corruption.
 log.similar,-- similar log repeat : x
 log.pngpna,PNA size is different from PNG, or PNA isn't grayscale : 
+log.lavfilter,You can try to install LAV Filters ( https://github.com/Nevcairiel/LAVFilters/releases ) and restart SSP to solve this problem.

**Comment by steve02081504** [comment]
> 
> 
> English message.txt diff:
> 
> @@ -53,6 +53,9 @@
> info.gcsakura.nocraftman,One of craftman/craftmanw/craftmanurl entries not found. Can't register ghost that has incomplete creator information.
> info.gcsakura.disconnect,Can't connect to Ghost Capter Sakura server.
> 
> +info.archivepassword.first,This archive/NAR is password protected.\nPlease input password.
> +info.archivepassword.retry,Password mismatch.\nPlease input correct password.
> +
> //Resource
> resource.common.yesno,Yes,No
> resource.common.okcancel,OK,Cancel
> 
> @@ -134,3 +137,4 @@
> log.moduleerror,Communication error. Possible file corruption.
> log.similar,-- similar log repeat : x
> log.pngpna,PNA size is different from PNG, or PNA isn't grayscale :
> +log.lavfilter,You can try to install LAV Filters ( https://github.com/Nevcairiel/LAVFilters/releases ) and restart SSP to solve this problem.

I'll take care of this in half an hour
thank you

**Comment by steve02081504** [comment]
done
