### ISSUE TITLE
SSP 2.5.58 message.txt update

### ISSUE THREAD

**Issue by ponapalt** [steve02081504/ssp-sinicization#9]
info.developer.timemachine,"Hook Current Time API (Timemachine)" function is activated.\nPlease use developer palette to resume normal operation.
info.url.ghostboot,Do you want to launch the ghost specified in the URL that you are trying to open?

**Comment by steve02081504** [comment]
Done, thanks for updating ssp😀
I've been busy with [other things](https://github.com/ELC-lang/ELC) lately, I'll regain some of my energy on ukagaka when I'm done👻
